import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import NavigationBar from "./navbar";
import Footer from "./footer";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <NavigationBar>
            {children}
            <Footer />
          </NavigationBar>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
